import React, { useState } from 'react';
import { View, Text, StyleSheet, ScrollView, Pressable, Linking, LayoutAnimation, Platform, UIManager } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import Animated, { FadeInDown } from 'react-native-reanimated';
import { useTheme, radii } from '../src/theme';

if (Platform.OS === 'android' && UIManager.setLayoutAnimationEnabledExperimental) {
  UIManager.setLayoutAnimationEnabledExperimental(true);
}

interface FAQItem {
  question: string;
  answer: string;
}

const FAQ_ITEMS: FAQItem[] = [
  {
    question: 'What is PriorAuth Buddy?',
    answer: 'PriorAuth Buddy is an educational tool that helps you understand and navigate the insurance prior authorization and appeals process. It uses AI to help you draft appeal letters, prepare for phone calls with your insurer and track your cases all in one place.',
  },
  {
    question: 'Is this legal advice?',
    answer: 'No. PriorAuth Buddy is strictly an educational tool. We do not provide legal, medical or insurance advice. The information and letters generated by the app are starting points to help you advocate for yourself. Always consult qualified professionals for legal or medical decisions and verify all information with your insurer before submitting anything.',
  },
  {
    question: 'How does the AI write appeal letters?',
    answer: 'When you provide details about your case (diagnosis, procedure, reason for denial, etc.), our AI analyzes that information along with common appeal strategies and relevant guidelines to draft a personalized appeal letter. The letter is a starting point that you should review, edit and personalize before sending. Your case data is processed by the AI but is not retained after the letter is generated.',
  },
  {
    question: 'Is my medical information safe?',
    answer: 'Yes. Your case data and medical information are stored locally on your device. We do not upload or store health records, diagnoses or protected health information on our servers. When you generate an appeal letter, your data is sent to our AI provider for processing but is not retained afterward. See our Privacy Policy for full details.',
  },
  {
    question: 'How do I cancel my subscription?',
    answer: 'You can cancel your PriorAuth Buddy Pro subscription at any time through your device\'s app store settings. On iPhone, go to Settings > Your Name > Subscriptions. On Android, go to Google Play Store > Subscriptions. Cancellation takes effect at the end of your current billing period and you will retain Pro access until then.',
  },
  {
    question: 'What if my appeal doesn\'t work?',
    answer: 'Appeal outcomes depend on many factors outside our control, including your insurer\'s policies, your specific medical situation and the documentation provided. If your first appeal is denied, you often have the right to file additional levels of appeal or request an external review. PriorAuth Buddy can help you understand your options at each stage. Remember, we cannot guarantee any specific outcome.',
  },
  {
    question: 'How do I delete my account?',
    answer: 'You can delete your account from the Profile tab in the app. This will permanently remove your email, preferences and all server-side data associated with your account. Since case data is stored locally on your device, you may also want to uninstall the app to remove that data. You can also email us at support@priorauthbuddy.com and we will delete your account within 30 days.',
  },
  {
    question: 'What insurers do you support?',
    answer: 'PriorAuth Buddy is designed to work with any US health insurer. Our AI generates appeal letters based on general best practices, federal regulations (like the Affordable Care Act appeals process) and insurer-specific strategies where available. The app works for private insurance, employer-sponsored plans and marketplace plans.',
  },
];

function FAQCard({ item, index }: { item: FAQItem; index: number }) {
  const { colors, typography } = useTheme();
  const [expanded, setExpanded] = useState(false);

  const toggle = () => {
    LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);
    setExpanded(!expanded);
  };

  return (
    <Animated.View entering={FadeInDown.delay(100 + index * 50).springify()}>
      <Pressable onPress={toggle} style={[styles.faqCard, { backgroundColor: colors.surface }]}>
        <View style={styles.faqHeader}>
          <Text style={[typography.body, { color: colors.text, flex: 1, fontWeight: '600' }]}>{item.question}</Text>
          <Text style={[typography.h3, { color: colors.primary }]}>{expanded ? '−' : '+'}</Text>
        </View>
        {expanded && (
          <Text style={[typography.body, { color: colors.textSecondary, lineHeight: 24, marginTop: 12 }]}>
            {item.answer}
          </Text>
        )}
      </Pressable>
    </Animated.View>
  );
}

export default function HelpScreen() {
  const { colors, typography } = useTheme();
  const router = useRouter();

  return (
    <SafeAreaView style={[styles.container, { backgroundColor: colors.background }]}>
      <View style={styles.header}>
        <Pressable onPress={() => router.back()} style={styles.backButton}>
          <Text style={[typography.body, { color: colors.primary }]}>← Back</Text>
        </Pressable>
        <Text style={[typography.h1, { color: colors.text }]}>Help & Support</Text>
      </View>

      <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
        <Animated.View entering={FadeInDown.springify()} style={[styles.contactCard, { backgroundColor: `${colors.primary}15`, borderColor: `${colors.primary}40` }]}>
          <Text style={[typography.h3, { color: colors.primary, marginBottom: 8 }]}>💬 Need Help?</Text>
          <Text style={[typography.body, { color: colors.text, lineHeight: 24 }]}>
            Can't find what you're looking for? Our support team is here to help.
          </Text>
          <Pressable
            onPress={() => Linking.openURL('mailto:support@priorauthbuddy.com')}
            style={[styles.contactButton, { backgroundColor: colors.primary }]}
          >
            <Text style={[typography.body, { color: '#FFFFFF', fontWeight: '700', textAlign: 'center' }]}>
              Email support@priorauthbuddy.com
            </Text>
          </Pressable>
          <Text style={[typography.caption, { color: colors.textTertiary, marginTop: 8 }]}>
            We typically respond within 24 hours.
          </Text>
        </Animated.View>

        <Animated.View entering={FadeInDown.delay(50).springify()}>
          <Text style={[typography.h3, { color: colors.textSecondary, marginBottom: 12 }]}>FREQUENTLY ASKED QUESTIONS</Text>
        </Animated.View>

        {FAQ_ITEMS.map((item, index) => (
          <FAQCard key={index} item={item} index={index} />
        ))}

        <View style={styles.footer}>
          <Text style={[typography.caption, { color: colors.textTertiary, textAlign: 'center' }]}>
            PriorAuth Buddy v1.0.0
          </Text>
          <Text style={[typography.caption, { color: colors.textTertiary, textAlign: 'center' }]}>
            2026 Forge Partners Inc. All rights reserved.
          </Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  header: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 12, gap: 4 },
  backButton: { paddingVertical: 8 },
  content: { paddingHorizontal: 20, paddingBottom: 100, gap: 12 },
  contactCard: { borderRadius: radii.card, padding: 20, borderWidth: 1, marginBottom: 8 },
  contactButton: { marginTop: 16, paddingVertical: 14, borderRadius: radii.button, alignItems: 'center' },
  faqCard: { borderRadius: radii.card, padding: 16 },
  faqHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 },
  footer: { marginTop: 24, gap: 4, paddingBottom: 20 },
});
